name: Python application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Get model
      run: |
        # Install Git LFS from the official source
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
        sudo apt-get install -y git-lfs
        git lfs install --skip-repo
        # Get model
        mkdir -p models/codebert && \
        git clone https://huggingface.co/nnikolaidis/java-ku models/codebert && \
        cd models/codebert && git lfs pull && \
        rm -rf .git
    - name: Test with pytest
      run: |
        python -m unittest discover